/**
 * Seed catalog: Pokémon TCG + Disney Lorcana sample data.
 * Production: replace with sync jobs from Pokémon TCG API, Lorcana sources, etc.
 */

import type { Card, CardList, UserCard } from "@/lib/types";
import { estimateUnitValue } from "@/lib/utils";

const now = () => new Date().toISOString();

function card(
  partial: Omit<Card, "createdAt" | "updatedAt" | "searchText" | "language"> & {
    language?: string;
  }
): Card {
  const language = partial.language ?? "en";
  const searchText = [
    partial.name,
    partial.setName,
    partial.setCode,
    partial.number,
    partial.rarity,
    partial.artist,
    ...(partial.types ?? []),
    partial.game,
  ]
    .filter(Boolean)
    .join(" ")
    .toLowerCase();

  return {
    ...partial,
    language,
    searchText,
    createdAt: now(),
    updatedAt: now(),
  };
}

/** Representative Pokémon cards across popular sets */
export const SEED_CARDS: Card[] = [
  // Scarlet & Violet 151
  card({
    id: "sv3pt5-025",
    game: "pokemon",
    setId: "sv3pt5",
    setName: "Scarlet & Violet 151",
    setCode: "MEW",
    number: "025",
    name: "Pikachu",
    rarity: "common",
    artist: "OKACHEKE",
    types: ["Lightning"],
    imageUrl: "https://images.pokemontcg.io/sv3pt5/25.png",
    marketPrice: 0.35,
  }),
  card({
    id: "sv3pt5-025-ir",
    game: "pokemon",
    setId: "sv3pt5",
    setName: "Scarlet & Violet 151",
    setCode: "MEW",
    number: "173",
    name: "Pikachu",
    rarity: "illustration_rare",
    artist: "HYOGONOSUKE",
    types: ["Lightning"],
    imageUrl: "https://images.pokemontcg.io/sv3pt5/173.png",
    marketPrice: 48.0,
  }),
  card({
    id: "sv3pt5-150",
    game: "pokemon",
    setId: "sv3pt5",
    setName: "Scarlet & Violet 151",
    setCode: "MEW",
    number: "150",
    name: "Mewtwo",
    rarity: "rare",
    artist: "Anesaki Dynamic",
    types: ["Psychic"],
    imageUrl: "https://images.pokemontcg.io/sv3pt5/150.png",
    marketPrice: 1.2,
  }),
  card({
    id: "sv3pt5-151",
    game: "pokemon",
    setId: "sv3pt5",
    setName: "Scarlet & Violet 151",
    setCode: "MEW",
    number: "151",
    name: "Mew ex",
    rarity: "double_rare",
    artist: "aky CG Works",
    types: ["Psychic"],
    imageUrl: "https://images.pokemontcg.io/sv3pt5/151.png",
    marketPrice: 4.5,
  }),
  card({
    id: "sv3pt5-193",
    game: "pokemon",
    setId: "sv3pt5",
    setName: "Scarlet & Violet 151",
    setCode: "MEW",
    number: "193",
    name: "Mew ex",
    rarity: "special_illustration_rare",
    artist: "aky CG Works",
    types: ["Psychic"],
    imageUrl: "https://images.pokemontcg.io/sv3pt5/193.png",
    marketPrice: 185.0,
  }),
  card({
    id: "sv3pt5-004",
    game: "pokemon",
    setId: "sv3pt5",
    setName: "Scarlet & Violet 151",
    setCode: "MEW",
    number: "004",
    name: "Charmander",
    rarity: "common",
    artist: "GIDORA",
    types: ["Fire"],
    imageUrl: "https://images.pokemontcg.io/sv3pt5/4.png",
    marketPrice: 0.25,
  }),
  card({
    id: "sv3pt5-168",
    game: "pokemon",
    setId: "sv3pt5",
    setName: "Scarlet & Violet 151",
    setCode: "MEW",
    number: "168",
    name: "Charmander",
    rarity: "illustration_rare",
    artist: "miki kudo",
    types: ["Fire"],
    imageUrl: "https://images.pokemontcg.io/sv3pt5/168.png",
    marketPrice: 32.0,
  }),
  card({
    id: "sv3pt5-006",
    game: "pokemon",
    setId: "sv3pt5",
    setName: "Scarlet & Violet 151",
    setCode: "MEW",
    number: "006",
    name: "Charizard ex",
    rarity: "double_rare",
    artist: "5ban Graphics",
    types: ["Fire"],
    imageUrl: "https://images.pokemontcg.io/sv3pt5/6.png",
    marketPrice: 12.0,
  }),
  card({
    id: "sv3pt5-199",
    game: "pokemon",
    setId: "sv3pt5",
    setName: "Scarlet & Violet 151",
    setCode: "MEW",
    number: "199",
    name: "Charizard ex",
    rarity: "special_illustration_rare",
    artist: "5ban Graphics",
    types: ["Fire"],
    imageUrl: "https://images.pokemontcg.io/sv3pt5/199.png",
    marketPrice: 320.0,
  }),
  card({
    id: "sv3pt5-007",
    game: "pokemon",
    setId: "sv3pt5",
    setName: "Scarlet & Violet 151",
    setCode: "MEW",
    number: "007",
    name: "Squirtle",
    rarity: "common",
    artist: "Mitsuhiro Arita",
    types: ["Water"],
    imageUrl: "https://images.pokemontcg.io/sv3pt5/7.png",
    marketPrice: 0.3,
  }),
  card({
    id: "sv3pt5-170",
    game: "pokemon",
    setId: "sv3pt5",
    setName: "Scarlet & Violet 151",
    setCode: "MEW",
    number: "170",
    name: "Squirtle",
    rarity: "illustration_rare",
    artist: "OKACHEKE",
    types: ["Water"],
    imageUrl: "https://images.pokemontcg.io/sv3pt5/170.png",
    marketPrice: 28.0,
  }),
  card({
    id: "sv3pt5-001",
    game: "pokemon",
    setId: "sv3pt5",
    setName: "Scarlet & Violet 151",
    setCode: "MEW",
    number: "001",
    name: "Bulbasaur",
    rarity: "common",
    artist: "Yoriyuki Ikegami",
    types: ["Grass"],
    imageUrl: "https://images.pokemontcg.io/sv3pt5/1.png",
    marketPrice: 0.4,
  }),
  card({
    id: "sv3pt5-166",
    game: "pokemon",
    setId: "sv3pt5",
    setName: "Scarlet & Violet 151",
    setCode: "MEW",
    number: "166",
    name: "Bulbasaur",
    rarity: "illustration_rare",
    artist: "Yoriyuki Ikegami",
    types: ["Grass"],
    imageUrl: "https://images.pokemontcg.io/sv3pt5/166.png",
    marketPrice: 35.0,
  }),
  // Obsidian Flames
  card({
    id: "sv3-199",
    game: "pokemon",
    setId: "sv3",
    setName: "Obsidian Flames",
    setCode: "OBF",
    number: "199",
    name: "Charizard ex",
    rarity: "special_illustration_rare",
    artist: "aky CG Works",
    types: ["Darkness"],
    imageUrl: "https://images.pokemontcg.io/sv3/199.png",
    marketPrice: 95.0,
  }),
  card({
    id: "sv3-125",
    game: "pokemon",
    setId: "sv3",
    setName: "Obsidian Flames",
    setCode: "OBF",
    number: "125",
    name: "Charizard ex",
    rarity: "double_rare",
    artist: "5ban Graphics",
    types: ["Darkness"],
    imageUrl: "https://images.pokemontcg.io/sv3/125.png",
    marketPrice: 8.5,
  }),
  // Paldean Fates
  card({
    id: "sv4pt5-227",
    game: "pokemon",
    setId: "sv4pt5",
    setName: "Paldean Fates",
    setCode: "PAF",
    number: "227",
    name: "Iono",
    rarity: "special_illustration_rare",
    artist: "DOM",
    types: ["Trainer"],
    imageUrl: "https://images.pokemontcg.io/sv4pt5/227.png",
    marketPrice: 110.0,
  }),
  card({
    id: "sv4pt5-055",
    game: "pokemon",
    setId: "sv4pt5",
    setName: "Paldean Fates",
    setCode: "PAF",
    number: "055",
    name: "Charmander",
    rarity: "common",
    artist: "sui",
    types: ["Fire"],
    imageUrl: "https://images.pokemontcg.io/sv4pt5/55.png",
    marketPrice: 0.5,
  }),
  // Prismatic Evolutions
  card({
    id: "sv8pt5-100",
    game: "pokemon",
    setId: "sv8pt5",
    setName: "Prismatic Evolutions",
    setCode: "PRE",
    number: "100",
    name: "Umbreon ex",
    rarity: "special_illustration_rare",
    artist: "Yuu Nishida",
    types: ["Darkness"],
    imageUrl: "https://images.pokemontcg.io/sv8pt5/100.png",
    marketPrice: 420.0,
  }),
  card({
    id: "sv8pt5-028",
    game: "pokemon",
    setId: "sv8pt5",
    setName: "Prismatic Evolutions",
    setCode: "PRE",
    number: "028",
    name: "Eevee",
    rarity: "common",
    artist: "Kagemaru Himeno",
    types: ["Colorless"],
    imageUrl: "https://images.pokemontcg.io/sv8pt5/28.png",
    marketPrice: 0.45,
  }),
  // Classic / Base Set era reference
  card({
    id: "base1-4",
    game: "pokemon",
    setId: "base1",
    setName: "Base Set",
    setCode: "BS",
    number: "4",
    name: "Charizard",
    rarity: "rare",
    artist: "Mitsuhiro Arita",
    types: ["Fire"],
    imageUrl: "https://images.pokemontcg.io/base1/4.png",
    marketPrice: 350.0,
  }),
  card({
    id: "base1-58",
    game: "pokemon",
    setId: "base1",
    setName: "Base Set",
    setCode: "BS",
    number: "58",
    name: "Pikachu",
    rarity: "common",
    artist: "Mitsuhiro Arita",
    types: ["Lightning"],
    imageUrl: "https://images.pokemontcg.io/base1/58.png",
    marketPrice: 12.0,
  }),

  // Disney Lorcana — The First Chapter
  card({
    id: "lorcana-tfc-001",
    game: "lorcana",
    setId: "lorcana-tfc",
    setName: "The First Chapter",
    setCode: "TFC",
    number: "1",
    name: "Ariel - On Human Legs",
    rarity: "common",
    artist: "Alice Pisoni",
    types: ["Storyborn", "Hero", "Princess"],
    marketPrice: 0.25,
  }),
  card({
    id: "lorcana-tfc-005",
    game: "lorcana",
    setId: "lorcana-tfc",
    setName: "The First Chapter",
    setCode: "TFC",
    number: "5",
    name: "Stitch - Rock Star",
    rarity: "super_rare",
    artist: "Nicola Saviori",
    types: ["Storyborn", "Hero", "Alien"],
    marketPrice: 45.0,
  }),
  card({
    id: "lorcana-tfc-017",
    game: "lorcana",
    setId: "lorcana-tfc",
    setName: "The First Chapter",
    setCode: "TFC",
    number: "17",
    name: "Elsa - Snow Queen",
    rarity: "legendary",
    artist: "Matthew Robert Davies",
    types: ["Dreamborn", "Hero", "Queen", "Sorcerer"],
    marketPrice: 28.0,
  }),
  card({
    id: "lorcana-tfc-008",
    game: "lorcana",
    setId: "lorcana-tfc",
    setName: "The First Chapter",
    setCode: "TFC",
    number: "8",
    name: "Mickey Mouse - Brave Little Tailor",
    rarity: "legendary",
    artist: "Cristian Romero",
    types: ["Dreamborn", "Hero"],
    marketPrice: 35.0,
  }),
  card({
    id: "lorcana-tfc-192",
    game: "lorcana",
    setId: "lorcana-tfc",
    setName: "The First Chapter",
    setCode: "TFC",
    number: "192",
    name: "Hades - Infernal Schemer",
    rarity: "legendary",
    artist: "Matthew Robert Davies",
    types: ["Dreamborn", "Villain", "Deity"],
    marketPrice: 22.0,
  }),
  card({
    id: "lorcana-tfc-204",
    game: "lorcana",
    setId: "lorcana-tfc",
    setName: "The First Chapter",
    setCode: "TFC",
    number: "204e",
    name: "Elsa - Snow Queen",
    rarity: "enchanted",
    artist: "Matthew Robert Davies",
    types: ["Dreamborn", "Hero", "Queen", "Sorcerer"],
    marketPrice: 280.0,
  }),
  // Ursula's Return
  card({
    id: "lorcana-ur-001",
    game: "lorcana",
    setId: "lorcana-ur",
    setName: "Ursula's Return",
    setCode: "UR",
    number: "1",
    name: "Ursula - Sea Witch",
    rarity: "legendary",
    artist: "LadyRedArt",
    types: ["Storyborn", "Villain", "Sorcerer"],
    marketPrice: 18.0,
  }),
  card({
    id: "lorcana-ur-042",
    game: "lorcana",
    setId: "lorcana-ur",
    setName: "Ursula's Return",
    setCode: "UR",
    number: "42",
    name: "Genie - On the Job",
    rarity: "super_rare",
    artist: "Javier Salas",
    types: ["Storyborn", "Ally"],
    marketPrice: 8.5,
  }),
  // Missing cards for master-set demo (151 set fillers user may not own)
  card({
    id: "sv3pt5-094",
    game: "pokemon",
    setId: "sv3pt5",
    setName: "Scarlet & Violet 151",
    setCode: "MEW",
    number: "094",
    name: "Gengar",
    rarity: "uncommon",
    artist: "Anesaki Dynamic",
    types: ["Psychic"],
    imageUrl: "https://images.pokemontcg.io/sv3pt5/94.png",
    marketPrice: 0.8,
  }),
  card({
    id: "sv3pt5-143",
    game: "pokemon",
    setId: "sv3pt5",
    setName: "Scarlet & Violet 151",
    setCode: "MEW",
    number: "143",
    name: "Snorlax",
    rarity: "uncommon",
    artist: "HYOGONOSUKE",
    types: ["Colorless"],
    imageUrl: "https://images.pokemontcg.io/sv3pt5/143.png",
    marketPrice: 0.6,
  }),
  card({
    id: "sv3pt5-131",
    game: "pokemon",
    setId: "sv3pt5",
    setName: "Scarlet & Violet 151",
    setCode: "MEW",
    number: "131",
    name: "Lapras",
    rarity: "uncommon",
    artist: "Sekio",
    types: ["Water"],
    imageUrl: "https://images.pokemontcg.io/sv3pt5/131.png",
    marketPrice: 0.55,
  }),
  card({
    id: "sv3pt5-065",
    game: "pokemon",
    setId: "sv3pt5",
    setName: "Scarlet & Violet 151",
    setCode: "MEW",
    number: "065",
    name: "Alakazam ex",
    rarity: "double_rare",
    artist: "PLANETA Mochizuki",
    types: ["Psychic"],
    imageUrl: "https://images.pokemontcg.io/sv3pt5/65.png",
    marketPrice: 3.2,
  }),
];

const DEMO_USER = "demo-user";

function uc(
  partial: Omit<UserCard, "userId" | "createdAt" | "updatedAt" | "listIds"> & {
    listIds?: string[];
  }
): UserCard {
  const cardData = SEED_CARDS.find((c) => c.id === partial.cardId);
  const estimatedValue = estimateUnitValue(
    cardData?.marketPrice,
    partial.condition,
    partial.isGraded,
    partial.gradeCompany,
    partial.grade
  );
  return {
    ...partial,
    userId: DEMO_USER,
    listIds: partial.listIds ?? ["list-collection"],
    estimatedValue,
    createdAt: now(),
    updatedAt: now(),
  };
}

/** Demo collection for the local-first MVP */
export const SEED_USER_CARDS: UserCard[] = [
  uc({
    id: "uc-1",
    cardId: "sv3pt5-025-ir",
    quantity: 1,
    condition: "NM",
    language: "en",
    variant: "illustration_rare",
    isGraded: false,
    purchasePrice: 42,
    purchaseDate: "2024-06-12",
  }),
  uc({
    id: "uc-2",
    cardId: "sv3pt5-193",
    quantity: 1,
    condition: "NM",
    language: "en",
    variant: "special_illustration_rare",
    isGraded: true,
    gradeCompany: "PSA",
    grade: "10",
    certNumber: "12345678",
    purchasePrice: 210,
    purchaseDate: "2024-08-01",
    notes: "Centered well, investment hold",
    listIds: ["list-collection", "list-investment"],
  }),
  uc({
    id: "uc-3",
    cardId: "sv3pt5-168",
    quantity: 2,
    condition: "NM",
    language: "en",
    variant: "illustration_rare",
    isGraded: false,
    purchasePrice: 28,
    purchaseDate: "2024-05-20",
  }),
  uc({
    id: "uc-4",
    cardId: "sv3pt5-199",
    quantity: 1,
    condition: "LP",
    language: "en",
    variant: "special_illustration_rare",
    isGraded: false,
    purchasePrice: 290,
    purchaseDate: "2024-04-10",
    notes: "Minor whitening bottom edge",
  }),
  uc({
    id: "uc-5",
    cardId: "sv3pt5-166",
    quantity: 1,
    condition: "NM",
    language: "en",
    variant: "illustration_rare",
    isGraded: false,
    purchasePrice: 30,
  }),
  uc({
    id: "uc-6",
    cardId: "sv3pt5-170",
    quantity: 1,
    condition: "NM",
    language: "en",
    variant: "illustration_rare",
    isGraded: false,
    purchasePrice: 25,
  }),
  uc({
    id: "uc-7",
    cardId: "sv3-199",
    quantity: 1,
    condition: "NM",
    language: "en",
    variant: "special_illustration_rare",
    isGraded: true,
    gradeCompany: "CGC",
    grade: "9.5",
    purchasePrice: 80,
    listIds: ["list-collection", "list-trade"],
  }),
  uc({
    id: "uc-8",
    cardId: "sv4pt5-227",
    quantity: 1,
    condition: "NM",
    language: "en",
    variant: "special_illustration_rare",
    isGraded: false,
    purchasePrice: 95,
    listIds: ["list-collection", "list-for-sale"],
  }),
  uc({
    id: "uc-9",
    cardId: "sv8pt5-100",
    quantity: 1,
    condition: "NM",
    language: "en",
    variant: "special_illustration_rare",
    isGraded: false,
    purchasePrice: 380,
    listIds: ["list-collection", "list-investment"],
  }),
  uc({
    id: "uc-10",
    cardId: "base1-4",
    quantity: 1,
    condition: "MP",
    language: "en",
    variant: "holo",
    isGraded: false,
    purchasePrice: 200,
    notes: "Unlimited Base Set holo, played",
  }),
  uc({
    id: "uc-11",
    cardId: "base1-58",
    quantity: 3,
    condition: "LP",
    language: "en",
    variant: "normal",
    isGraded: false,
    purchasePrice: 8,
  }),
  uc({
    id: "uc-12",
    cardId: "sv3pt5-025",
    quantity: 4,
    condition: "NM",
    language: "en",
    variant: "normal",
    isGraded: false,
    purchasePrice: 0.25,
  }),
  uc({
    id: "uc-13",
    cardId: "sv3pt5-004",
    quantity: 2,
    condition: "NM",
    language: "en",
    variant: "normal",
    isGraded: false,
    purchasePrice: 0.2,
  }),
  uc({
    id: "uc-14",
    cardId: "sv3pt5-001",
    quantity: 2,
    condition: "NM",
    language: "en",
    variant: "normal",
    isGraded: false,
    purchasePrice: 0.3,
  }),
  uc({
    id: "uc-15",
    cardId: "sv3pt5-007",
    quantity: 2,
    condition: "NM",
    language: "en",
    variant: "normal",
    isGraded: false,
    purchasePrice: 0.25,
  }),
  uc({
    id: "uc-16",
    cardId: "sv3pt5-150",
    quantity: 1,
    condition: "NM",
    language: "en",
    variant: "holo",
    isGraded: false,
    purchasePrice: 1.0,
  }),
  uc({
    id: "uc-17",
    cardId: "sv3pt5-151",
    quantity: 1,
    condition: "NM",
    language: "en",
    variant: "holo",
    isGraded: false,
    purchasePrice: 4.0,
  }),
  uc({
    id: "uc-18",
    cardId: "sv3pt5-006",
    quantity: 1,
    condition: "LP",
    language: "en",
    variant: "holo",
    isGraded: false,
    purchasePrice: 10,
    listIds: ["list-collection", "list-trade"],
  }),
  // Lorcana
  uc({
    id: "uc-19",
    cardId: "lorcana-tfc-005",
    quantity: 1,
    condition: "NM",
    language: "en",
    variant: "normal",
    isGraded: false,
    purchasePrice: 40,
  }),
  uc({
    id: "uc-20",
    cardId: "lorcana-tfc-204",
    quantity: 1,
    condition: "NM",
    language: "en",
    variant: "enchanted",
    isGraded: true,
    gradeCompany: "CGC",
    grade: "10",
    purchasePrice: 250,
    listIds: ["list-collection", "list-investment"],
  }),
  uc({
    id: "uc-21",
    cardId: "lorcana-tfc-017",
    quantity: 2,
    condition: "NM",
    language: "en",
    variant: "normal",
    isGraded: false,
    purchasePrice: 22,
  }),
  uc({
    id: "uc-22",
    cardId: "lorcana-tfc-008",
    quantity: 1,
    condition: "NM",
    language: "en",
    variant: "normal",
    isGraded: false,
    purchasePrice: 30,
    listIds: ["list-collection", "list-trade"],
  }),
  uc({
    id: "uc-23",
    cardId: "lorcana-ur-001",
    quantity: 1,
    condition: "LP",
    language: "en",
    variant: "normal",
    isGraded: false,
    purchasePrice: 15,
  }),
  uc({
    id: "uc-24",
    cardId: "sv3-125",
    quantity: 2,
    condition: "NM",
    language: "en",
    variant: "holo",
    isGraded: false,
    purchasePrice: 7,
    listIds: ["list-collection", "list-trade"],
  }),
];

export const SEED_LISTS: CardList[] = [
  {
    id: "list-collection",
    userId: DEMO_USER,
    name: "Main Collection",
    type: "collection",
    description: "Primary binder inventory",
    isPublic: false,
    itemCount: SEED_USER_CARDS.length,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "list-want",
    userId: DEMO_USER,
    name: "Want List",
    type: "want",
    description: "Cards I'm hunting",
    isPublic: false,
    shareSlug: undefined,
    itemCount: 3,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "list-trade",
    userId: DEMO_USER,
    name: "Trade Binder",
    type: "trade",
    description: "Available for trade",
    isPublic: true,
    shareSlug: "demo-trade-binder",
    itemCount: SEED_USER_CARDS.filter((c) => c.listIds.includes("list-trade"))
      .length,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "list-for-sale",
    userId: DEMO_USER,
    name: "For Sale",
    type: "for_sale",
    isPublic: false,
    itemCount: SEED_USER_CARDS.filter((c) =>
      c.listIds.includes("list-for-sale")
    ).length,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "list-investment",
    userId: DEMO_USER,
    name: "Investment Holds",
    type: "investment",
    description: "Long-term holds — do not trade lightly",
    isPublic: false,
    itemCount: SEED_USER_CARDS.filter((c) =>
      c.listIds.includes("list-investment")
    ).length,
    createdAt: now(),
    updatedAt: now(),
  },
];

/** Cards on want list (catalog refs, not necessarily owned) */
export const SEED_WANT_CARD_IDS = [
  "sv3pt5-094",
  "sv3pt5-143",
  "sv3pt5-131",
  "sv3pt5-065",
  "lorcana-tfc-192",
];

export const DEMO_USER_ID = DEMO_USER;
